core/openapi/schemas/processSummary.yaml
core/standard/clause_7_core.adoc

align project object links with WFS3 design pattern

---

README.md

Add the ZOO-Project Swagger UI link to README.md

---

core/18-062.adoc
core/annex-history.adoc
core/clause_2_conformance.adoc
core/clause_7_core.adoc
core/clause_7a_ogc-process-description.adoc
core/recommendations/README.md
core/recommendations/core/REC_ogc-process-description.adoc
core/requirements/core/REQ_process-success.adoc
core/requirements/ogc-process-description/REQ_json-encoding.adoc
core/requirements/requirements_class_ogc-process-description.adoc

Make the use of the OGC process description a recommendation and seperate it out into its own conformance class.

OGC Process Description conformance class

---

core/openapi/responses/ExecuteSync.yaml

Fixes dereferencing for synchronous Execute requests.

fix ref to Execute results/exceptions

---

core/requirements/html/REQ_content.adoc

Fixes #114

---

core/clause_10_job_list.adoc
core/clause_7_core.adoc
core/clause_7a_ogc-process-description.adoc
core/recommendations/core/PER_api-definition-uri.adoc
core/requirements/core/REQ_api-definition-op.adoc

Minor fixes from march 9 2021

---

core/openapi/schemas/statusInfo.yaml

Issue #142 - Add process id to job status

---

core/clause_7_core.adoc
core/requirements/core/REQ_job-creation-input.adoc

Issue #129 - Clarify list vs. object for inputs with multiplicity

---

core/clause_7b_security-considerations.adoc
core/recommendations/job-list/REC_access-control-job-list.adoc

Issue #104 - Add recommendation regarding access control for the /jobs endpoint

---

core/clause_7_core.adoc
core/examples/json/StatusInfo.json
core/openapi/schemas/statusInfo.yaml
core/recommendations/core/REC_job-status.adoc

Issue 184: Add optional date-time fields that track milestones in the life cycle of a job.

---

core/examples/json/ProcessDescription.json
core/openapi/ogcapi-processes-1.yaml
core/openapi/responses/ExecuteAsync.yaml
core/openapi/responses/ExecuteSync.yaml
core/openapi/responses/Results.yaml
core/openapi/responses/swagger/ProcessDescription.yaml
core/openapi/schemas/binaryInputValue.yaml
core/openapi/schemas/exception.yaml
core/openapi/schemas/inlineOrRefData.yaml
core/openapi/schemas/inputValueNoObject.yaml
core/openapi/schemas/swagger/inputDescription.yaml
core/openapi/schemas/swagger/outputDescription.yaml
core/openapi/schemas/swagger/process.yaml
core/openapi/schemas/swagger/schema.yaml

Small fixes that should solve various validation issues encoutred when using the openapi-cli and, spectral tools. Some files has been added also to get the swagger-ui required files available.

Small fixes

---

core/clause_3_references.adoc
core/clause_7a_ogc-process-description.adoc
core/examples/json/ProcessDescription.json
core/recommendations/ogc-process-description/REC_format-key.adoc
core/recommendations/ogc-process-description/REC_format-short-code.adoc
core/recommendations/ogc-process-description/REC_format-value-registration.adoc

Although this is not strictly necessary is a good practice and makes parsing and interpreting the input/output easier.

Add the contentMediaType facet to the GeoJSON feature collection inputs/outputs.

---

implementations.adoc

Add a link for PyWPS `OGC API - Processes` implementation

Update implementations.adoc [PyWPS]

---

implementations.adoc

Update implementations.doc with Hexagon server and client links.

Update implementations.doc with Hexagon

---

core/openapi/parameters/processIdPathParam.yaml
core/openapi/schemas/results.yaml

Here is the correct definition of the processPathParam.

Correct schema for processIdPathParam

---

core/examples/json/Execute.json
core/examples/json/ProcessDescription.json
core/examples/json/Result.json
core/sections/clause_7_core.adoc
core/sections/clause_8_ogc-process-description.adoc

- application/tiff -> image/tiff
- application/jp2 -> image/jp2

examples; 7 & 8: Correct wrong media types

---

extensions/deploy_replace_undeploy/README.md

Many details were out of date or simply incorrect.
I also propose a summary description that was missing for this extension. Feel free to edit further as desired.

update Part 2 readme with relevant details

---

core/openapi/schemas/schema.yaml

Update the definitions of exclusiveMinimum/exclusiveMaximum. to conform to JSON-schema versions above draft 4.

Update the definitions of exclusiveMinimum/exclusiveMaximum.

---

workshops/2023/code-sprint-1/2023_09_code_sprint_registration.adoc

This PR adds myself as a participant to the upcoming Sept. 2023 virtual sprint

Added ricardo silva as a participant to upcoming sprint

---

workshops/2023/code-sprint-1/2023_09_code_sprint_registration.adoc

2023_09_code_sprint_registration.adoc

---

workshops/2023/code-sprint-1/2023_09_code_sprint_registration.adoc

Register for upcoming code sprint.

code sprint registration for @jkeifer

---

workshops/2023/code-sprint-1/2023_09_code_sprint_registration.adoc

Registration for Alexander Pilz for 52° North from Münster to the OGC API Code Sprint.

Registration for the OGC API Code Sprint 

---

workshops/2023/code-sprint-1/2023_09_code_sprint_registration.adoc

Added my name to the list of registrants for the September 2023 OGC API Code Sprint

Registration to the September 2023 OGC Code Sprint

---

core/requirements/job-list/REQ_duration-def.adoc
openapi/ogcapi-processes.bundled.json
openapi/parameters/processes-core/maxDuration.yaml
openapi/parameters/processes-core/minDuration.yaml

Change minDuration/maxDuration to integers.

---

extensions/deploy_replace_undeploy/standard/requirements/cwl/deploy/REQ_exception-workflow-not-found.adoc

The file for the requirement `/req/cwl/deploy/exception-workflow-not-found` was missing.

Add missing file

---

openapi/schemas/processes-core/statusInfo.yaml

Add exception member.

---

openapi/schemas/processes-core/metadata.yaml

Allow metadata to be referenced or encoded inline.

---

openapi/ogcapi-processes.bundled.json
openapi/paths/processes-workflows/pExecution-workflows.yaml

- Added 204 for Part3 version of execute

openapi: regenerated bundle with swagger-cli (update.sh)

---

extensions/job_management/standard/abstract_tests/jm/create/ATS_post-op.adoc

fix invalid part 4 requirement rename

---

core/recommendations/ogc-process-description/REC_links.adoc
core/sections/clause_5_conventions.adoc
core/sections/clause_8_ogc-process-description.adoc

Add service link recommendation.

---

core/sections/clause_0_front_material.adoc
extensions/deploy_replace_undeploy/standard/sections/clause_0_front_material.adoc
extensions/job_management/standard/sections/clause_0_front_material.adoc
extensions/workflows/sections/clause_0_front_material.adoc

 fix missing/align name of contributions
