core/openapi/schemas/jobInfo.yaml
Changed the required field 'status' to 'infos' to match the valid properties in jobInfo.yaml.
=> Fixes 61 - mismatch in required properties for jobInfo.yaml

core/examples/json/JobList.json
The example for JobList seems to be wrong and to use the previously defined syntaxe.
This pull request should solve the issue.
=> Fix old syntaxe in JobList example used from the file: clause_10_job_list.adoc

core/abstract_tests/core/ATS_conformance-op.adoc, core/abstract_tests/core/ATS_landingpage-success.adoc, core/clause_5_conventions.adoc, core/examples/json/JobList.json, core/examples/json/LandingPage.json, core/examples/json/ProcessDescription.json, core/examples/json/ProcessList.json, core/openapi/responses/LandingPage.yaml, core/recommendations/job-list/REC_job-list-landing-page.adoc, core/requirements/core/REQ_landingpage-success.adoc
Update all OAPIR-specific link relations to use the pattern `http://www.opengis.net/def/rel/ogc/1.0/{rel}`.  Eventually these will be
registered with the OGC-NA.
=> Update OAPIP-specific link relations to be URIs to be compliant with OGC-NA policies.

core/openapi/schemas/results.yaml
There is no multiplicity for outputs. Arrays can be returned by defining the schema in the output description as such.
=> results.yaml: Removed array (#219)

core/abstract_tests/ATS_class_core.adoc, core/abstract_tests/core/ATS_job-creation-success-sync-raw-mixed-multi.adoc, core/abstract_tests/core/ATS_job-results-success-async-raw-mixed-multi.adoc, core/clause_7_core.adoc, core/requirements/core/REQ_job-creation-success-sync-raw-mixed-multi.adoc, core/requirements/core/REQ_job-results-success-async-raw-mixed-multi.adoc, core/requirements/core/REQ_job-results-success-async-raw-value-multi.adoc
Add requirements and abstract tests to handle the case where the negotiated execution mode is sync or async, the requested response is raw, more that 1 output is requested and a mix of transmission modes (value or reference) are requested.
=> Handling a mix of value and reference transmissions modes with raw output.

core/openapi/schemas/jobControlOptions.yaml
In the OGC process description the supported execution modes must be explicitly listed
so there is no need for a default.
=> Remove default value for job control options.  

core/abstract_tests/ATS_class_job-list.adoc, core/abstract_tests/job-list/ATS_datetime-response.adoc, core/abstract_tests/job-list/ATS_duration-response.adoc, core/abstract_tests/job-list/ATS_processid-mandatory.adoc, core/clause_10_job_list.adoc, core/recommendations/core/REC_job-status.adoc, core/requirements/job-list/REQ_processid-mandatory.adoc
If the server supports the Job Lists conformance class then the processID property should be mandatory.  Forgot to make this change when I was adding the query parameters to the `/jobs` endpoint.  Fixed now.
=> Oppsie!  Forgot to make processID mandatory if the server supports the Job Lists conformance class.

core/examples/json/ProcessDescription.json
Required field did not make sense for an input as :
```json
{ 
"inputs": {
"measureInput": {
"value": {
"measurement": 123,
"uom": "m",
}
}
}
}
=> fix required 'value' for 'measurement' in example process description

core/sections/clause_7_core.adoc
Shouldn't the async execution response code be 201 rather than 200?
(as it is currently in [7.11.4 Table 11](https://docs.ogc.org/is/18-062r2/18-062r2.html#toc32))
=> Async execution response: 201 rather than 200

extensions/workflows/openapi/README.md
Changed SwaggerUI link to use source JSON API definition from official OGC master branch now that #PR 301 has been merged.
@pvretano
=> Fixed workflows OpenAPI Readme

core/openapi/responses/InvalidParameter.yaml, core/openapi/responses/NotAllowed.yaml, core/openapi/responses/NotFound.yaml, core/openapi/responses/NotSupported.yaml, core/openapi/responses/ServerError.yaml
As described [here](https://github.com/opengeospatial/ogcapi-common/issues/318), we should use "application/problem+json" as Content-Type for exception.
=> Use application/problem+json as specified in section 6.1 of the IETF RFC 7807

core/requirements/oas30/REQ_oas-definition-1.adoc
Fix broken wording for OAS requirement.  The current wording does not make it quite explicit that `rel=service-desc` should be used for the JSON version of the API document and that `rel=service-doc` should be used for the HTML version of the API document.
=> Fix broken wording.

openapi/ogcapi-processes.bundled.json, openapi/schemas/processes-core/subscriber.yaml
This PR fixes the naming of a required property on the subscriber schema.
=> Fix successUrl -> successUri.

openapi/ogcapi-processes.bundled.json, openapi/ogcapi-processes.yaml, openapi/schemas/processes-core/descriptionType.yaml
The `additionalParameters` stuff was added to OWS common ages ago to allow extensibility in XML without the need to rewrite the XML schemas each time.
For OAProc, which mainly uses JSON, there is no need for  this since the `additionalProperties` parameter (being `true` by default) allows additional keys to be added as required thus making the entire `additionalParameters` structure unnecessary.
This PR removes all references to `additionalParameters`.
Closes #351
=> Remove references to addtionalParameters.

.gitignore, extensions/deploy_replace_undeploy/standard/sections/clause_7_apppkg.adoc
The `ogcapppkg` schema reference seemed to be missing one `../` to find the correct location.
=> fix invalid reference adoc OGC AppPkg schema

core/requirements/core/REQ_process-execute-inputs.adoc, openapi/schemas/processes-core/inputDescription.yaml
Allow value passing to be specified per input rather than requiring thes erver to support both by-value and by-refernce in all cases.  The default value for the `valuePassing` parameter is `["byValue","byReference"]` to maintain backward compatability.
Closes #369
=> Value passing in an execute request.

core/requirements/dismiss/REQ_job-dismiss-status.adoc, core/sections/clause_14_dismiss.adoc
=> Clarify what happens to a job when dismissed.

extensions/deploy_replace_undeploy/standard/recommendations/deploy-replace-undeploy/package/REC_response-cwl.adoc, extensions/deploy_replace_undeploy/standard/recommendations/deploy-replace-undeploy/package/REC_response-ogcapppkg.adoc, extensions/deploy_replace_undeploy/standard/requirements/cwl/package/REQ_response-body.adoc, extensions/deploy_replace_undeploy/standard/requirements/deploy-replace-undeploy/package/REQ_get-op.adoc, extensions/deploy_replace_undeploy/standard/requirements/deploy-replace-undeploy/package/REQ_response-body.adoc, extensions/deploy_replace_undeploy/standard/requirements/deploy-replace-undeploy/package/REQ_response-success.adoc, extensions/deploy_replace_undeploy/standard/requirements/ogcapppkg/package/REQ_response-body.adoc, extensions/deploy_replace_undeploy/standard/sections/annex_history.adoc, extensions/deploy_replace_undeploy/standard/sections/clause_6_deploy_replace_undeploy.adoc, extensions/deploy_replace_undeploy/standard/sections/clause_7_apppkg.adoc, extensions/deploy_replace_undeploy/standard/sections/clause_9_cwl.adoc, openapi/paths/processes-dru/pPackage.yaml
As discussed on April 15, 2024, during the SWG meeting, we propose the following additions.
Add /processes/{processId}/package path for accessing the formal description used to deploy a process.
Add specific recommendations and requirements for the OGC Application Package and CWL conformance classes.
=> Fix issue #282

openapi/schemas/processes-job-management/processes-type.yaml
The `enum` defined in the `processes-type.yaml` is now replaced by `example`. With it, the `type` attribute is no longer restricted to predefined values, easing potential integration in other Standards (ref. #447).
=> Typo in processes-types.yaml (closes #447)

openapi/schemas/processes-workflows/fieldsModifiers.yaml
- add `filter-lang` and `filter-crs` for Part 3 field modifiers
- add a basic CQL2-JSON variant for `filter`
- fix indents of the schema
=> update schema of Part 3 field modifiers

core/sections/clause_8_ogc-process-description.adoc
=> Extend list of format codes.

core/examples/json/ProcessDescription.json, core/examples/json/bbox.json, core/recommendations/html/PER_media-types.adoc, core/recommendations/json/PER_media-types.adoc, core/requirements/html/REQ_definition.adoc, core/requirements/json/REQ_definition.adoc, core/sections/clause_10_encodings.adoc, core/sections/clause_7_core.adoc, openapi/responses/processes-job-management/rLocked.yaml, openapi/schemas/processes-core/inputValueNoObject.yaml, openapi/schemas/processes-core/statusCode.yaml, openapi/schemas/processes-job-management/statusCode.yaml
Closes #271 
Closes #315 
Closes #350 
Closes #416 
Closes #478
=> Clarify 200 responses for JSON and HTML content.

core/recommendations/core/PER_job-success.adoc, core/sections/clause_18_profile.adoc, core/sections/clause_7_core.adoc
Removed the relevant requirements/recommendations and added a small informative text block indicating that the profile mechanism can be used to negotiate for other representations.
Closes #517
=> Remote requirements/recommendations about "profileEntityType".
